# Generated by Django 2.1.1 on 2020-02-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200221_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='blue1.jpg', upload_to=''),
        ),
    ]
