# Generated by Django 2.1.1 on 2020-02-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstep',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
